const express = require('express')
const router = express.Router()
const userRouter = require('./user')
const statisticRouter = require('./statistic')
const voucherRouter = require('./voucher')
const orderRouter = require('./order')
const mailRouter = require('./mail')
const viewRouter = require('./view-history')
const brandRouter = require('./brand')
const laptopRouter = require('./laptop')
const installmentRouter = require('./installment')
const userAddressRouter = require('./user-address')
const commentRouter  = require('./comment')
const bookingRouter = require('./booking')
const payosRouter = require('./payos')
const verifyJWT = require('../../middlewares/verifyJWT')
const elasticRouter = require('./elastic')

router.use('/users', userRouter)
router.use('/comments', commentRouter)
router.use('/user-address', userAddressRouter)
router.use('/installments', installmentRouter)
router.use('/laptops', laptopRouter)
router.use('/brands', brandRouter)
router.use('/statistics', statisticRouter)
router.use('/vouchers', voucherRouter)
router.use('/orders', orderRouter)
router.use('/mail', mailRouter)
router.use('/view-history', viewRouter)
router.use('/payos', payosRouter)
router.use('/booking', bookingRouter)
router.use('/elastic', elasticRouter)

module.exports = router
